FROM tomcat:8.5-jre8

MAINTAINER deegree TMC <tmc@deegree.org>

# set deegree version
ENV DEEGREE_VERSION 3.3.20
ENV GEOSYNC_VERSION 1.2
ENV RELEASE_DATE 20170316

EXPOSE 8080

# download deegree 
RUN wget https://github.com/kartverket/geosynkronisering/releases/download/${GEOSYNC_VERSION}/${RELEASE_DATE}_Deegree_${DEEGREE_VERSION}.war -O /usr/local/tomcat/webapps/deegree-webservices.war
# RUN wget https://jdbc.postgresql.org/download/postgresql-42.2.5.jar


# run tomcat
CMD ["catalina.sh", "run"]
# CMD ["rm", "/usr/local/tomcat/webapps/deegree-webservices/"]