version: '3.7'

services:
  postgresql:
    depends_on:
      - subscriber_config
    container_name: geosynchronization-db-${epsg}-${dataset}
    image: geosynchronization/postgis:${epsg}-${dataset}
    volumes:
      - geosynchronization-db-volume:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ${dataset}_${epsg}

  deegree:
    depends_on:
      - postgresql
    container_name: geosynchronization-wfs-${epsg}-${dataset}
    image: geosynchronization/deegree3:${epsg}-${dataset}
    ports:
      - "8181:8080"
    restart: always
    command: sh -c "sleep 120; /usr/local/tomcat/bin/catalina.sh run"

  subscriber:
    depends_on:
      - deegree
    container_name: geosynchronization-subscriber-${epsg}-${dataset}
    image: geosynchronization/coresubscriber
    volumes:
      # - provider:/provider
      - ./provider:/provider
    restart: always
    environment:
      epsg: ${epsg}
      dataset: ${dataset}
    command: sh -c "crontab /app/cron; crond -f"

  subscriber_config:
    container_name: geosynchronization-config-${epsg}-${dataset}
    image: geosynchronization/coresubscriber
    volumes:
      # - provider:/${providerName}
      - ./provider:/provider
    environment:
      providerurl: ${providerurl}
      username: ${username}
      password: ${password}
      epsg: ${epsg}
      dataset: ${dataset}
    command: sh -c "mkdir -p /provider; if [ -s /provider/config.xml ]; then exit 0; fi; dotnet CORESubscriber.dll add ${providerurl} ${username} ${password} /provider/config.template.xml;  cat /provider/config.template.xml | sed 's/<subscribed>False<\/subscribed>/<subscribed>True<\/subscribed>/gi' | sed 's/<wfsClient><\/wfsClient>/<wfsClient>http:\/\/geosynchronization-wfs-${epsg}-${dataset}:8080\/services\/wfs<\/wfsClient>/gi' > /provider/config.xml || exit 1"

volumes:
  # provider:
  geosynchronization-db-volume: