version: '3.3'

services:
  postgresql:
    container_name: deegreepostgis_db
    build: ./
    image: deegreepostgis
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: development

  deegree:
    container_name: deegreepostgis_wfs
    depends_on:
      - postgresql
    image: deegree/deegree3-docker
    ports:
      - "8181:8080"
    volumes:
      - ./workspace:/deegree
    restart: always
    environment:
      DEEGREE_WORKSPACE_ROOT: /deegree

volumes:
  db_volume: