version: '3.7'

services:
  postgresql:
    container_name: deegreepostgis_db
    build: 
      context: ./
      dockerfile: Dockerfile_db
    image: deegreepostgis
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: development

  deegree:
    container_name: deegreepostgis_wfs
    build: 
      context: ./
      dockerfile: Dockerfile_wfs
    depends_on:
      - postgresql
    # image: deegree/deegree3-docker
    image: deegreepostgis_wfs
    ports:
      - "8181:8080"
    volumes:
      - ./srs/5972/workspace:/deegree
    restart: always
    environment:
      DEEGREE_WORKSPACE_ROOT: /deegree

  # deegree_cli:
  #   container_name: deegreepostgis_deegree_cli
  #   image: geosynchronization/deegreeschemareader
  #   volumes:
  #     - ./data:/data
  #   command: ./convert.sh 5972 http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Tiltak/4.6/FKB-Tiltak46.xsd tiltak

volumes:
  db_volume: