version: '3.7'

services:
  postgresql:
    depends_on:
      - subscriber_config
    container_name: geosynchronization-db-${epsg}-${dataset}
    # build: 
    #   context: ./
    #   dockerfile: dockerfiles/Dockerfile_db_${epsg}_${dataset}
    image: geosynchronization/postgis:${epsg}-${dataset}
    volumes:
      - geosynchronization-db-volume:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ${dataset}_${epsg}

  deegree:
    depends_on:
      - postgresql
    container_name: geosynchronization-wfs-${epsg}-${dataset}
    image: geosynchronization/deegree3:${epsg}-${dataset}
    depends_on:
      - postgresql
    ports:
      - "8181:8080"
    restart: always
    # volumes:
    #   - ./dockerfiles/srs/${epsg}/${dataset}/workspace:/deegree
    # environment:
    #   DEEGREE_WORKSPACE_ROOT: /deegree

  subscriber:
    depends_on:
      - deegree
    container_name: geosynchronization-subscriber-${epsg}-${dataset}
    image: geosynchronization/coresubscriber
    volumes:
      # - providers:/providers/${providerName}
      - ./subscriber/providers/${providerName}:/provider
      - ./subscriber/cron:/cron
    environment:
      epsg: ${epsg}
      dataset: ${dataset}
    command: sh -c "crontab /cron/cron; crond -f"

  subscriber_config:
    container_name: geosynchronization-config-${epsg}-${dataset}
    image: geosynchronization/coresubscriber
    # volumes:
    #   providers:/providers
    volumes:
      - ./subscriber/providers:/providers
    environment:
      providerurl: ${providerurl}
      username: ${username}
      password: ${password}
      epsg: ${epsg}
      dataset: ${dataset}
    command: sh -c "mkdir -p /providers/${providerName}; if [ -s /providers/${providerName}/config.xml ]; then exit 0; fi; dotnet CORESubscriber.dll add ${providerurl} ${username} ${password} /providers/${providerName}/config.template.xml;  cat /providers/${providerName}/config.template.xml | sed 's/<subscribed>False<\/subscribed>/<subscribed>True<\/subscribed>/gi' | sed 's/<wfsClient><\/wfsClient>/<wfsClient>http:\/\/geosynchronization-wfs-${epsg}-${dataset}:8080\/services\/wfs<\/wfsClient>/gi' > /providers/${providerName}/config.xml"

volumes:
  # providers:
  geosynchronization-db-volume: