version: '3.7'

services:
  postgresql:
    depends_on:
      - subscriber_config
    container_name: geosynchronization-db-${epsg}-${dataset}
    build: 
      context: ./
      dockerfile: Dockerfile_db_${epsg}_${dataset}
    image: geosynchronization/postgis-${epsg}-${dataset}
    volumes:
      - geosynchronization-db-volume-${epsg}-${dataset}:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ${dataset}_${epsg}

  deegree:
    depends_on:
      - postgresql
    container_name: geosynchronization-wfs-${epsg}-${dataset}
    image: geosynchronization/deegree3
    depends_on:
      - postgresql
    ports:
      - "8181:8080"
    volumes:
      - ./srs/${epsg}/${dataset}/workspace:/deegree
    restart: always
    environment:
      DEEGREE_WORKSPACE_ROOT: /deegree

  subscriber:
    depends_on:
      - deegree
    container_name: geosynchronization-subscriber
    image: geosynchronization/coresubscriber
    volumes:
      - ./subscriber/providers/${providerName}:/provider
      - ./subscriber/cron:/cron
    environment:
      epsg: ${epsg}
      dataset: ${dataset}
    command: sh -c "crontab /cron/cron; crond -f"

  subscriber_config:
    container_name: geosynchronization-config
    image: geosynchronization/coresubscriber
    volumes:
      - ./subscriber/providers/${providerName}:/provider
    environment:
      providerurl: ${providerurl}
      username: ${username}
      password: ${password}
      epsg: ${epsg}
      dataset: ${dataset}
    command: sh -c "if [ -s /provider/config.xml ]; then exit 0; fi; dotnet CORESubscriber.dll add $${providerurl} $${username} $${password} /provider/config.template.xml;  cat /provider/config.template.xml | sed 's/<subscribed>False<\/subscribed>/<subscribed>True<\/subscribed>/gi' | sed 's/<wfsClient><\/wfsClient>/<wfsClient>http:\/\/geosynchronization-wfs-${epsg}-${dataset}:8080\/services\/wfs<\/wfsClient>/gi' > /provider/config.xml"

volumes:
  geosynchronization-db-volume-5972-fkb:
  geosynchronization-db-volume-5973-fkb:
  geosynchronization-db-volume-5975-fkb:
  geosynchronization-db-volume-5972-reguleringsplan:
  geosynchronization-db-volume-5973-reguleringsplan:
  geosynchronization-db-volume-5975-reguleringsplan: