version: '3.7'

services:
  postgresql:
    container_name: deegreepostgis_db
    build: 
      context: ./
      dockerfile: Dockerfile_db
    image: deegreepostgis
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: development

  deegree:
    container_name: deegreepostgis-wfs
    image: geosynchronization/deegree3
    depends_on:
      - postgresql
    ports:
      - "8181:8080"
    volumes:
      - ./srs/5972/workspace:/deegree
    restart: always
    environment:
      DEEGREE_WORKSPACE_ROOT: /deegree

  # subscriber:
  #   container_name: deegreepostgis_subscriber
  #   image: geosynchronization/coresubscriber
  #   volumes:
  #     - ./subscriber:/data
  #   command: ["dotnet", "CORESubscriber.dll", "add", "${providerurl}", "${username}", "${password}", "/data/${providerSettings}.xml"]

volumes:
  db_volume: